SELECT CLIENT_NO, NAME, CITY
FROM CLIENT_MASTER;

SELECT *
FROM PRODUCT_MASTER
WHERE QTY_NO_HAND<10;


SELECT *
FROM SALESMAN_MASTER
WHERE CITY='Maharashtra';

SELECT SALE_ORDER_DETAILS.*
FROM SALE_ORDER_DETAILS, SALES_ORDER_SALESMAN_MASTER
WHERE SALE_ORDER_DETAILS.ORDER_NO=SALES_ORDER.ORDER_NO AND SALES_ORDER.SALESMAN_NO=SALESMAN_MASTER.SALESMAN_NO AND SALESMAN_MASTER.SALESMAN_NAME='surya';


SELECT SALE_ORDER_DETAILS.*
FROM SALE_ORDER_DETAILS, SALES_ORDER
WHERE SALES_ORDER.ORDER_NO=SALE_ORDER_DETAILS.ORDER_NO AND SALES_ORDER.ORDER_STATUS='In Process';

SELECT COUNT(ORDER_NO) ORDERS
FROM SALES_ORDER;


SELECT AVG(COST_PRICE) CP_AVERAGE, AVG(SEL_PRICE) SP_AVERAGE
FROM PRODUCT_MASTER;

SELECT NAME, CITY, STATE
FROM CLIENT_MASTER;
WHERE STATE!='Maharashtra';
