CREATE DATABASE PDDEXP2;
use PDDEXP2;

CREATE TABLE STUDENT
(
    ROLL_NO INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(20),
    ADDRESS VARCHAR(30),
    DOB VARCHAR(10),
    MARK1 FLOAT,
    MARK2 FLOAT,
    MARK3 FLOAT
);
CREATE TABLE EMPLOYEE
(
    ENCODE INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(20),
    GENDER CHAR,
    DOB VARCHAR(10),
    DOJ VARCHAR(10),
    SALARY FLOAT
);
